### ISSUE TITLE
회원가입 피그마 수정요청

### ISSUE THREAD

**Issue by woajun** [hyeonju-kim/Winterfoodies#11]
api/signup 리퀘스트 바디가 
{
  "password": "비밀번호",
  "phoneNumber": "휴대폰 번호",
  "username": "이메일"
}
으로 닉네임 대신 휴대폰 번호가 있습니다. 
의도하신 방향으로 api와 피그마 동기화 부탁드립니다.

**Comment by hyeonju-kim** [comment]
![image](https://github.com/hyeonju-kim/Winterfoodies/assets/58349668/59c46931-f384-49d3-803f-7c06a7049e85)

휴대폰번호는 넣는게 좋을 것 같아서 그대로 두고, 닉네임 추가했습니다.
