### ISSUE TITLE
별점순 조회가 없음

### ISSUE THREAD

**Issue by woajun** [hyeonju-kim/Winterfoodies#3]
인기순 검색결과
http://3.37.179.100:8080/api/main/2/popular?latitude=37.381798&longitude=126.800944
[
    {
        "id": 1,
        "name": "신천붕어빵",
        "basicAddress": "신천역 1번 출구",
        "avergeRating": 4
    },
    {
        "id": 2,
        "name": "대야붕어빵",
        "basicAddress": "대야역 1번 출구",
        "avergeRating": 5
    },
    {
        "id": 3,
        "name": "소새울호떡집",
        "basicAddress": "소새울역 1번 출구",
        "avergeRating": 5
    }
]
리뷰순 검색결과
http://3.37.179.100:8080/api/main/2/reviewstore?latitude=37.381798&longitude=126.800944

[
    {
        "id": 1,
        "name": "신천붕어빵",
        "basicAddress": "신천역 1번 출구",
        "avergeRating": 4
    },
    {
        "id": 2,
        "name": "대야붕어빵",
        "basicAddress": "대야역 1번 출구",
        "avergeRating": 5
    },
    {
        "id": 3,
        "name": "소새울호떡집",
        "basicAddress": "소새울역 1번 출구",
        "avergeRating": 5
    }
]

**Comment by hyeonju-kim** [comment]
완료
