### ISSUE TITLE
인기순, 리뷰순은 위경도를 받지않고있음

### ISSUE THREAD

**Issue by woajun** [hyeonju-kim/Winterfoodies#6]
인기순, 리뷰순이 위경도를 받지 않으면, 서울에서 부산에있는 가게까지 모든 데이터가 응답에 포함될것 같습니다

**Comment by hyeonju-kim** [comment]
가까운순을 제외한 인기순, 리뷰순, 평점순은 4km 내의 데이터만을 수집하도록 수정했습니다.
