### ISSUE TITLE
가게 상세 API 가게이름, 별점, 즐겨찾기 없음

### ISSUE THREAD

**Issue by woajun** [hyeonju-kim/Winterfoodies#7]

**Comment by woajun** [comment]
요청: /api/main/{storeId} 에 리뷰, 인포, 디테일등 가게 정보 전부 한번에 주실 수 있을까요?

**Comment by hyeonju-kim** [comment]
가게상세api -가게이름,별점,like 추가 완료.
리뷰, 인포는 따로 api가 있는데, 그 각각 api를 합쳐서 가게상세api를 사용하자는 말씀이실까요??
